controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50
    use_local_topics: true
    state_interfaces:
      - position
    interfaces:
      - Rotation/position
      - Pitch/position
      - Elbow/position
      - Wrist_Pitch/position
      - Wrist_Roll/position
      - Jaw/position

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - Rotation
      - Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll
      - Jaw
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    use_local_topics: true